### PR TITLE
Support for arbitrary case Named Colors

### LINKED ISSUE #134: Named colors with upper case letters are not recognized
According to [https://www.w3.org/TR/ttml1/#style-value-namedColor](https://www.w3.org/TR/ttml1/#style-value-namedColor) :

> For the purpose of parsing, a distinction must not be made between lower and upper case.

Yet, for exemple, `Cyan` is not detected.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #134

### CODE REVIEW

**Comment by VincentFTS** [comment]
I’m not sure that you should extend the lower case transformation to the other cases (HEX_COLOR_RE, DEC_COLOR_RE, DEC_COLORA_RE) since the specification doesn’t require it [
https://www.w3.org/TR/ttml1/#style-value-color](https://www.w3.org/TR/ttml1/#style-value-color)

**Comment by palemieux** [comment]
@VincentFTS `hexDigit` allows both upper- and lowercase, but I agree the code was not the most expressive.

**Comment by VincentFTS** [comment]
Why not using the m variable ?

`
if (m = NAMED_COLOR[str.toLowerCase()] !== undefined) {
  r = m;
}
`

**Comment by palemieux** [comment]
I like to avoid having completely different types/semantics assigned to the same variable. Looks good otherwise?

**Comment by VincentFTS** [comment]
Looks perfect !!

**Pull request merged**
