### PR TITLE
ebutts:linePadding emulated using border instead of padding

### LINKED ISSUE #137: Possible regression: linePadding and background opacity broken?
Hi,

I'm using imscJS via dash.js and it looks there is an issue with `ebutts:linePadding` and line background opacity.

Example:

```xml
<styl xml:id="paragraphStyle"
      tts:textAlign="start"
      tts:lineHeight="135%"
      ebutts:linePadding="0.2c" />

<style xml:id="spanStyle"
       tts:backgroundColor="#00000099"
       tts:color="#FFFFFF"
       tts:fontFamily="sans-serif"
       tts:fontSize="100%" />

<!-- -->

<p begin="00:00:02.459" end="00:00:02.726" xml:id="sub_5" region="r" style="paragraphStyle">
    <span style="spanStyle">Han trodde sig själv, och många med</span>
    <br/>
    <span style="spanStyle">honom, att </span>
</p>
```

screen shot 2018-11-30 at 13 05 05

The first and last letter on each row have a slightly darker background then the rest of the row. I suspect that this is caused by additive opacity of the spans.

Any ideas of how to solve this?

Thanks,
Anton

### PR DESCRIPTION
**Pull request by palemieux**
Closes #137

### CODE REVIEW

**Comment by palemieux** [comment]
Deployed at http://sandflow.com/imsc1proc/index.html

**Comment by carlanton** [comment]
Cool! It looks good in your demo, but with dash.js it still looks a bit off:

screen shot 2018-12-04 at 13 57 58

Here is the dash.js master with this patch: https://s3.eu-central-1.amazonaws.com/svt-dist-misc/ttml/demo.html


ttml file: https://s3.eu-central-1.amazonaws.com/svt-dist-misc/ttml/subs.xml

**Comment by palemieux** [comment]
@carlanton Looks like an issue with fractional pixels. I have pushed an update to PR that rounds to the nearest whole pixel.

**Comment by carlanton** [comment]
Right! Yes, it looks perfect now :)

**Pull request merged**
