### PR TITLE
Add support for itts:fillLineGap

### PR DESCRIPTION
**Pull request by palemieux**
As specified in [IMSC1.0.1](https://www.w3.org/TR/ttml-imsc1.0.1/)

### CODE REVIEW

**Comment by palemieux** [comment]
@EyalLavi Interested in testing this PR?

**Comment by EyalLavi** [comment]
Absolutely!

**Comment by palemieux** [comment]
@EyalLavi How's the review coming along?

**Comment by EyalLavi** [comment]
@palemieux sorry for the delay. With the (longish) file below, there seems to be an issue with filling the gap when the `<br/>` is between `<span>`s (the vertical gap between the background areas is expected):
image

Also, I am not sure about the expected behaviour for different ratios of line height to font size, but when combining different font sizes in the same paragraph, gaps are not always filled:
image

```xml
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling"
	xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
	xmlns:ebuttm="urn:ebu:tt:metadata" xmlns:ebutts="urn:ebu:tt:style" ttp:timeBase="media" xmlns:itts="http://www.w3.org/ns/ttml/profile/imsc1#styling"
	xml:lang="en-GB" ttp:cellResolution="20 20">
	<head>
		<styling>
			<style xml:id="p_wrap" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
			<style xml:id="p_noWrap" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="noWrap" itts:fillLineGap="true"/>
			<style xml:id="p_80pc" tts:lineHeight="80%" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
			<style xml:id="p_100pc" tts:lineHeight="100%" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
			<style xml:id="p_120pc" tts:lineHeight="120%" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
			<style xml:id="p_150pc" tts:lineHeight="150%" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
			<style xml:id="p_250pc" tts:lineHeight="250%" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
			<style xml:id="span" tts:color="#ffffff" tts:backgroundColor="#000000"/>
			<style xml:id="span_small" tts:fontSize="50%" tts:color="#ff0000" tts:backgroundColor="#000000"/>
			<style xml:id="span_large" tts:fontSize="150%" tts:color="#0000ff" tts:backgroundColor="#000000"/>
		</styling>
		<layout>
			<region xml:id="R1" tts:origin="10% 10%" tts:extent="80% 80%" tts:overflow="visible"/>
		</layout>
	</head>
	<body>
		<div>
			<p style="p_wrap" xml:id="subtitle1" region="R1" begin="00:00:00" end="00:00:05">
				tts:wrapOption = wrap
				<span style="span">Line break inside the span:<br/>Second line.</span>
				<span style="span">Line break between spans:</span><br/><span style="span">Second line.</span>
			</p>
			<p style="p_noWrap" xml:id="subtitle2" region="R1" begin="00:00:05" end="00:00:10">
				tts:wrapOption = noWrap
				<span style="span">Line break inside the span:<br/>Second line.</span>
				<span style="span">Line break between spans:</span><br/><span style="span">Second line.</span>
			</p>
			<p style="p_wrap" xml:id="subtitle3" region="R1" begin="00:00:10" end="00:00:15">
				ts:lineHeight="normal"
				<span style="span">!  "  #  $  %  &amp;  '  (  )  *  +  ,  -  .  <br/>/  0  1  2  3  4  5  6  7  8  9 :  ;  &gt;  =  &lt;  ?  @ </span>
				<span style="span_small">A  B  C  D  E  H  I </span>
				<span style="span">J  K  L  N  O  P  Q  R  S  T  U V  W  X  Y  Z  [  \  ]  ^  _  `  </span>
				<span style="span_large">a b c d  e  h  i  j  k  l  n  o  p  q  r</span>
				<span style="span">s  t  u  v  w  x  y  z  {  |  }  ~  ¡  ¢  £  ¥  §  ¤  ‘  “  «  ←  ↑  →  ↓<br/></span>
				<span style="span_large">°  ±  ²  ³  ×  µ  ¶  ·  ÷  ’  ”  »  ¼  ½  ¾  ¿  ́  ̂  ̃  ̄  ̆  ̇  ̈  ̊  ̧  ̋<br/></span>
				<span style="span_small">̨  ―  ¹  ®  ©  ™  ♪  ¬  ¦  ⅛  ⅜  ⅝  ⅞  Ω  Æ  Đ  ª  Ħ  Ĳ  Ŀ  Ł  Ø  Œ  Þ  Ŧ<br/>
						Ŋ  ŉ ĸ  æ  đ  ð  ħ  ı  ĳ  ŀ  ł  ø  œ  ß  þ  ŧ  ŋ</span>
			</p>
			<p style="p_100pc" xml:id="subtitle4" region="R1" begin="00:00:15" end="00:00:20">
				ts:lineHeight="100%"
				<span style="span">!  "  #  $  %  &amp;  '  (  )  *  +  ,  -  .  <br/>/  0  1  2  3  4  5  6  7  8  9 :  ;  &gt;  =  &lt;  ?  @ </span>
				<span style="span_small">A  B  C  D  E  H  I </span>
				<span style="span">J  K  L  N  O  P  Q  R  S  T  U V  W  X  Y  Z  [  \  ]  ^  _  `  </span>
				<span style="span_large">a b c d  e  h  i  j  k  l  n  o  p  q  r</span>
				<span style="span">s  t  u  v  w  x  y  z  {  |  }  ~  ¡  ¢  £  ¥  §  ¤  ‘  “  «  ←  ↑  →  ↓<br/></span>
				<span style="span_large">°  ±  ²  ³  ×  µ  ¶  ·  ÷  ’  ”  »  ¼  ½  ¾  ¿  ́  ̂  ̃  ̄  ̆  ̇  ̈  ̊  ̧  ̋<br/></span>
				<span style="span_small">̨  ―  ¹  ®  ©  ™  ♪  ¬  ¦  ⅛  ⅜  ⅝  ⅞  Ω  Æ  Đ  ª  Ħ  Ĳ  Ŀ  Ł  Ø  Œ  Þ  Ŧ<br/>
					Ŋ  ŉ ĸ  æ  đ  ð  ħ  ı  ĳ  ŀ  ł  ø  œ  ß  þ  ŧ  ŋ</span>
			</p>
			<p style="p_120pc" xml:id="subtitle5" region="R1" begin="00:00:20" end="00:00:25">
				ts:lineHeight="120%"
				<span style="span">!  "  #  $  %  &amp;  '  (  )  *  +  ,  -  .  <br/>/  0  1  2  3  4  5  6  7  8  9 :  ;  &gt;  =  &lt;  ?  @ </span>
				<span style="span_small">A  B  C  D  E  H  I </span>
				<span style="span">J  K  L  N  O  P  Q  R  S  T  U V  W  X  Y  Z  [  \  ]  ^  _  `  </span>
				<span style="span_large">a b c d  e  h  i  j  k  l  n  o  p  q  r</span>
				<span style="span">s  t  u  v  w  x  y  z  {  |  }  ~  ¡  ¢  £  ¥  §  ¤  ‘  “  «  ←  ↑  →  ↓<br/></span>
				<span style="span_large">°  ±  ²  ³  ×  µ  ¶  ·  ÷  ’  ”  »  ¼  ½  ¾  ¿  ́  ̂  ̃  ̄  ̆  ̇  ̈  ̊  ̧  ̋<br/></span>
				<span style="span_small">̨  ―  ¹  ®  ©  ™  ♪  ¬  ¦  ⅛  ⅜  ⅝  ⅞  Ω  Æ  Đ  ª  Ħ  Ĳ  Ŀ  Ł  Ø  Œ  Þ  Ŧ<br/>
					Ŋ  ŉ ĸ  æ  đ  ð  ħ  ı  ĳ  ŀ  ł  ø  œ  ß  þ  ŧ  ŋ</span>
			</p>
			<p style="p_80pc" xml:id="subtitle5" region="R1" begin="00:00:25" end="00:00:30">
				ts:lineHeight="80%"
				<span style="span">!  "  #  $  %  &amp;  '  (  )  *  +  ,  -  .  <br/>/  0  1  2  3  4  5  6  7  8  9 :  ;  &gt;  =  &lt;  ?  @ </span>
				<span style="span_small">A  B  C  D  E  H  I </span>
				<span style="span">J  K  L  N  O  P  Q  R  S  T  U V  W  X  Y  Z  [  \  ]  ^  _  `  </span>
				<span style="span_large">a b c d  e  h  i  j  k  l  n  o  p  q  r</span>
				<span style="span">s  t  u  v  w  x  y  z  {  |  }  ~  ¡  ¢  £  ¥  §  ¤  ‘  “  «  ←  ↑  →  ↓<br/></span>
				<span style="span_large">°  ±  ²  ³  ×  µ  ¶  ·  ÷  ’  ”  »  ¼  ½  ¾  ¿  ́  ̂  ̃  ̄  ̆  ̇  ̈  ̊  ̧  ̋<br/></span>
				<span style="span_small">̨  ―  ¹  ®  ©  ™  ♪  ¬  ¦  ⅛  ⅜  ⅝  ⅞  Ω  Æ  Đ  ª  Ħ  Ĳ  Ŀ  Ł  Ø  Œ  Þ  Ŧ<br/>
					Ŋ  ŉ ĸ  æ  đ  ð  ħ  ı  ĳ  ŀ  ł  ø  œ  ß  þ  ŧ  ŋ</span>
			</p>
			<p style="p_150pc" xml:id="subtitle6" region="R1" begin="00:00:30" end="00:00:35">
				ts:lineHeight="150%"
				<span style="span">!  "  #  $  %  &amp;  '  (  )  *  +  ,  -  .  <br/>/  0  1  2  3  4  5  6  7  8  9 :  ;  &gt;  =  &lt;  ?  @ </span>
				<span style="span_small">A  B  C  D  E  H  I </span>
				<span style="span">J  K  L  N  O  P  Q  R  S  T  U V  W  X  Y  Z  [  \  ]  ^  _  `  </span>
				<span style="span_large">a b c d  e  h  i  j  k  l  n  o  p  q  r</span>
				<span style="span">s  t  u  v  w  x  y  z  {  |  }  ~  ¡  ¢  £  ¥  §  ¤  ‘  “  «  ←  ↑  →  ↓<br/></span>
				<span style="span_large">°  ±  ²  ³  ×  µ  ¶  ·  ÷  ’  ”  »  ¼  ½  ¾  ¿  ́  ̂  ̃  ̄  ̆  ̇  ̈  ̊  ̧  ̋<br/></span>
				<span style="span_small">̨  ―  ¹  ®  ©  ™  ♪  ¬  ¦  ⅛  ⅜  ⅝  ⅞  Ω  Æ  Đ  ª  Ħ  Ĳ  Ŀ  Ł  Ø  Œ  Þ  Ŧ<br/>
					Ŋ  ŉ ĸ  æ  đ  ð  ħ  ı  ĳ  ŀ  ł  ø  œ  ß  þ  ŧ  ŋ</span>
			</p>
			<p style="p_250pc" xml:id="subtitle7" region="R1" begin="00:00:35" end="00:00:40">
				ts:lineHeight="250%"
				<span style="span">!  "  #  $  %  &amp;  '  (  )  *  +  ,  -  .  <br/>/  0  1  2  3  4  5  6  7  8  9 :  ;  &gt;  =  &lt;  ?  @ </span>
				<span style="span_small">A  B  C  D  E  H  I </span>
				<span style="span">J  K  L  N  O  P  Q  R  S  T  U V  W  X  Y  Z  [  \  ]  ^  _  `  </span>
				<span style="span_large">a b c d  e  h  i  j  k  l  n  o  p  q  r</span>
				<span style="span">s  t  u  v  w  x  y  z  {  |  }  ~  ¡  ¢  £  ¥  §  ¤  ‘  “  «  ←  ↑  →  ↓<br/></span>
				<span style="span_large">°  ±  ²  ³  ×  µ  ¶  ·  ÷  ’  ”  »  ¼  ½  ¾  ¿  ́  ̂  ̃  ̄  ̆  ̇  ̈  ̊  ̧  ̋<br/></span>
				<span style="span_small">̨  ―  ¹  ®  ©  ™  ♪  ¬  ¦  ⅛  ⅜  ⅝  ⅞  Ω  Æ  Đ  ª  Ħ  Ĳ  Ŀ  Ł  Ø  Œ  Þ  Ŧ<br/>
					Ŋ  ŉ ĸ  æ  đ  ð  ħ  ı  ĳ  ŀ  ł  ø  œ  ß  þ  ŧ  ŋ</span>
			</p>			
		</div>
	</body>
</tt>
```

**Comment by palemieux** [comment]
@EyalLavi Thanks! Will review.

**Comment by palemieux** [comment]
@EyalLavi Thanks for great example. I have pushed a fix to the missing line gaps.

**Comment by palemieux** [comment]
@EyalLavi The absence of background where the line break is in the source (between _line._ and _Line_) is expected since the line break is turned into a space, to which no background is applied.

**Comment by palemieux** [comment]
@EyalLavi Just a quick note to see if the revised PR resolved your observations?

**Comment by EyalLavi** [comment]
@palemieux looking great! As you say, the vertical gap where a `<br/>` exists between `<span>`s is expected. Thanks.

**Comment by palemieux** [comment]
@EyalLavi Thanks for the review. Any objection to adding the document at https://github.com/sandflow/imscJS/pull/78#issuecomment-381628115 to the IMSC test suite?

**Comment by EyalLavi** [comment]
@palemieux no problem but please use this version. Changes:
- Removed unused namespace references
- Fixed typos in text (not in code)
- Added copyright notice

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2018 BBC
    -->
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
    xmlns:ebuttm="urn:ebu:tt:metadata" ttp:timeBase="media"
    xmlns:itts="http://www.w3.org/ns/ttml/profile/imsc1#styling" xml:lang="en-GB"
    ttp:cellResolution="20 20">
    <head>
        <styling>
            <style xml:id="p_wrap" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif"
                tts:wrapOption="wrap" itts:fillLineGap="true"/>
            <style xml:id="p_noWrap" tts:fontSize="100%" tts:fontFamily="proportionalSansSerif"
                tts:wrapOption="noWrap" itts:fillLineGap="true"/>
            <style xml:id="p_80pc" tts:lineHeight="80%" tts:fontSize="100%"
                tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
            <style xml:id="p_100pc" tts:lineHeight="100%" tts:fontSize="100%"
                tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
            <style xml:id="p_120pc" tts:lineHeight="120%" tts:fontSize="100%"
                tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
            <style xml:id="p_150pc" tts:lineHeight="150%" tts:fontSize="100%"
                tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
            <style xml:id="p_250pc" tts:lineHeight="250%" tts:fontSize="100%"
                tts:fontFamily="proportionalSansSerif" tts:wrapOption="wrap" itts:fillLineGap="true"/>
            <style xml:id="span" tts:color="#ffffff" tts:backgroundColor="#000000"/>
            <style xml:id="span_small" tts:fontSize="50%" tts:color="#ff0000"
                tts:backgroundColor="#000000"/>
            <style xml:id="span_large" tts:fontSize="150%" tts:color="#0000ff"
                tts:backgroundColor="#000000"/>
        </styling>
        <layout>
            <region xml:id="R1" tts:origin="10% 10%" tts:extent="80% 80%" tts:overflow="visible"/>
        </layout>
    </head>
    <body>
        <div>
            <p style="p_wrap" xml:id="subtitle1" region="R1" begin="00:00:00" end="00:00:05">
                tts:wrapOption = wrap <span style="span">Line break inside the span:<br/>Second
                    line.</span>
                <span style="span">Line break between spans:</span><br/><span style="span">Second
                    line.</span>
            </p>
            <p style="p_noWrap" xml:id="subtitle2" region="R1" begin="00:00:05" end="00:00:10">
                tts:wrapOption = noWrap <span style="span">Line break inside the span:<br/>Second
                    line.</span>
                <span style="span">Line break between spans:</span><br/><span style="span">Second
                    line.</span>
            </p>
            <p style="p_wrap" xml:id="subtitle3" region="R1" begin="00:00:10" end="00:00:15">
                tts:lineHeight="normal" <span style="span">! " # $ % &amp; ' ( ) * + , - . <br/>/ 0 1
                    2 3 4 5 6 7 8 9 : ; &gt; = &lt; ? @ </span>
                <span style="span_small">A B C D E H I </span>
                <span style="span">J K L N O P Q R S T U V W X Y Z [ \ ] ^ _ ` </span>
                <span style="span_large">a b c d e h i j k l n o p q r</span>
                <span style="span">s t u v w x y z { | } ~ ¡ ¢ £ ¥ § ¤ ‘ “ « ← ↑ → ↓<br/></span>
                <span style="span_large">° ± ² ³ × µ ¶ · ÷ ’ ” » ¼ ½ ¾ ¿ ́ ̂ ̃ ̄ ̆ ̇ ̈ ̊ ̧
                    ̋<br/></span>
                <span style="span_small">̨ ― ¹ ® © ™ ♪ ¬ ¦ ⅛ ⅜ ⅝ ⅞ Ω Æ Đ ª Ħ Ĳ Ŀ Ł Ø Œ Þ Ŧ<br/> Ŋ ŉ
                    ĸ æ đ ð ħ ı ĳ ŀ ł ø œ ß þ ŧ ŋ</span>
            </p>
            <p style="p_100pc" xml:id="subtitle4" region="R1" begin="00:00:15" end="00:00:20">
                tts:lineHeight="100%" <span style="span">! " # $ % &amp; ' ( ) * + , - . <br/>/ 0 1 2
                    3 4 5 6 7 8 9 : ; &gt; = &lt; ? @ </span>
                <span style="span_small">A B C D E H I </span>
                <span style="span">J K L N O P Q R S T U V W X Y Z [ \ ] ^ _ ` </span>
                <span style="span_large">a b c d e h i j k l n o p q r</span>
                <span style="span">s t u v w x y z { | } ~ ¡ ¢ £ ¥ § ¤ ‘ “ « ← ↑ → ↓<br/></span>
                <span style="span_large">° ± ² ³ × µ ¶ · ÷ ’ ” » ¼ ½ ¾ ¿ ́ ̂ ̃ ̄ ̆ ̇ ̈ ̊ ̧
                    ̋<br/></span>
                <span style="span_small">̨ ― ¹ ® © ™ ♪ ¬ ¦ ⅛ ⅜ ⅝ ⅞ Ω Æ Đ ª Ħ Ĳ Ŀ Ł Ø Œ Þ Ŧ<br/> Ŋ ŉ
                    ĸ æ đ ð ħ ı ĳ ŀ ł ø œ ß þ ŧ ŋ</span>
            </p>
            <p style="p_120pc" xml:id="subtitle5" region="R1" begin="00:00:20" end="00:00:25">
                tts:lineHeight="120%" <span style="span">! " # $ % &amp; ' ( ) * + , - . <br/>/ 0 1 2
                    3 4 5 6 7 8 9 : ; &gt; = &lt; ? @ </span>
                <span style="span_small">A B C D E H I </span>
                <span style="span">J K L N O P Q R S T U V W X Y Z [ \ ] ^ _ ` </span>
                <span style="span_large">a b c d e h i j k l n o p q r</span>
                <span style="span">s t u v w x y z { | } ~ ¡ ¢ £ ¥ § ¤ ‘ “ « ← ↑ → ↓<br/></span>
                <span style="span_large">° ± ² ³ × µ ¶ · ÷ ’ ” » ¼ ½ ¾ ¿ ́ ̂ ̃ ̄ ̆ ̇ ̈ ̊ ̧
                    ̋<br/></span>
                <span style="span_small">̨ ― ¹ ® © ™ ♪ ¬ ¦ ⅛ ⅜ ⅝ ⅞ Ω Æ Đ ª Ħ Ĳ Ŀ Ł Ø Œ Þ Ŧ<br/> Ŋ ŉ
                    ĸ æ đ ð ħ ı ĳ ŀ ł ø œ ß þ ŧ ŋ</span>
            </p>
            <p style="p_80pc" xml:id="subtitle5" region="R1" begin="00:00:25" end="00:00:30">
                tts:lineHeight="80%" <span style="span">! " # $ % &amp; ' ( ) * + , - . <br/>/ 0 1 2
                    3 4 5 6 7 8 9 : ; &gt; = &lt; ? @ </span>
                <span style="span_small">A B C D E H I </span>
                <span style="span">J K L N O P Q R S T U V W X Y Z [ \ ] ^ _ ` </span>
                <span style="span_large">a b c d e h i j k l n o p q r</span>
                <span style="span">s t u v w x y z { | } ~ ¡ ¢ £ ¥ § ¤ ‘ “ « ← ↑ → ↓<br/></span>
                <span style="span_large">° ± ² ³ × µ ¶ · ÷ ’ ” » ¼ ½ ¾ ¿ ́ ̂ ̃ ̄ ̆ ̇ ̈ ̊ ̧
                    ̋<br/></span>
                <span style="span_small">̨ ― ¹ ® © ™ ♪ ¬ ¦ ⅛ ⅜ ⅝ ⅞ Ω Æ Đ ª Ħ Ĳ Ŀ Ł Ø Œ Þ Ŧ<br/> Ŋ ŉ
                    ĸ æ đ ð ħ ı ĳ ŀ ł ø œ ß þ ŧ ŋ</span>
            </p>
            <p style="p_150pc" xml:id="subtitle6" region="R1" begin="00:00:30" end="00:00:35">
                tts:lineHeight="150%" <span style="span">! " # $ % &amp; ' ( ) * + , - . <br/>/ 0 1 2
                    3 4 5 6 7 8 9 : ; &gt; = &lt; ? @ </span>
                <span style="span_small">A B C D E H I </span>
                <span style="span">J K L N O P Q R S T U V W X Y Z [ \ ] ^ _ ` </span>
                <span style="span_large">a b c d e h i j k l n o p q r</span>
                <span style="span">s t u v w x y z { | } ~ ¡ ¢ £ ¥ § ¤ ‘ “ « ← ↑ → ↓<br/></span>
                <span style="span_large">° ± ² ³ × µ ¶ · ÷ ’ ” » ¼ ½ ¾ ¿ ́ ̂ ̃ ̄ ̆ ̇ ̈ ̊ ̧
                    ̋<br/></span>
                <span style="span_small">̨ ― ¹ ® © ™ ♪ ¬ ¦ ⅛ ⅜ ⅝ ⅞ Ω Æ Đ ª Ħ Ĳ Ŀ Ł Ø Œ Þ Ŧ<br/> Ŋ ŉ
                    ĸ æ đ ð ħ ı ĳ ŀ ł ø œ ß þ ŧ ŋ</span>
            </p>
            <p style="p_250pc" xml:id="subtitle7" region="R1" begin="00:00:35" end="00:00:40">
                tts:lineHeight="250%" <span style="span">! " # $ % &amp; ' ( ) * + , - . <br/>/ 0 1 2
                    3 4 5 6 7 8 9 : ; &gt; = &lt; ? @ </span>
                <span style="span_small">A B C D E H I </span>
                <span style="span">J K L N O P Q R S T U V W X Y Z [ \ ] ^ _ ` </span>
                <span style="span_large">a b c d e h i j k l n o p q r</span>
                <span style="span">s t u v w x y z { | } ~ ¡ ¢ £ ¥ § ¤ ‘ “ « ← ↑ → ↓<br/></span>
                <span style="span_large">° ± ² ³ × µ ¶ · ÷ ’ ” » ¼ ½ ¾ ¿ ́ ̂ ̃ ̄ ̆ ̇ ̈ ̊ ̧
                    ̋<br/></span>
                <span style="span_small">̨ ― ¹ ® © ™ ♪ ¬ ¦ ⅛ ⅜ ⅝ ⅞ Ω Æ Đ ª Ħ Ĳ Ŀ Ł Ø Œ Þ Ŧ<br/> Ŋ ŉ
                    ĸ æ đ ð ħ ı ĳ ŀ ł ø œ ß þ ŧ ŋ</span>
            </p>
        </div>
    </body>
</tt>
```

**Pull request merged**
